### ISSUE TITLE
access rights policy

### ISSUE THREAD

**Issue by pebau** [FAIRiCUBE/collaboration-platform#1]
We need to have a common policy for the data we offer - for the project partners, the outside world, and at some time for post-project. 

Currently, the various components have implemented their individual policies without a clear plan and without synchronization. Based on a central access policy document the components can align so that  access rights appear coherent to the users.

Please add mote assignees as necessary, I might have missed partners that should have a say here.

**Comment by pebau** [comment]
just saw that I had created a [similar issue](https://github.com/FAIRiCUBE/FAIRiCUBE-Hub-issue-tracker/issues/34) already - @KathiSchleidt please decide in which repo it is more appropriate, then I close the other.

**Comment by KathiSchleidt** [comment]
@pebau please try and use the correct repo, this issue has nothing to do with the collaboration platform
Not relevant here, leaving the version on [FAIRiCUBE-Hub-issue-tracker](https://github.com/FAIRiCUBE/FAIRiCUBE-Hub-issue-tracker/issues/34)
